-- MySQL Script generated by MySQL Workbench
-- Sat Dec 26 12:20:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rtl433
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rtl433` ;

-- -----------------------------------------------------
-- Schema rtl433
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rtl433` DEFAULT CHARACTER SET latin1 ;
USE `rtl433` ;

-- -----------------------------------------------------
-- Table `rtl433`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rtl433`.`location` ;

CREATE TABLE IF NOT EXISTS `rtl433`.`location` (
  `id` VARCHAR(25) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rtl433`.`locationTemperature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rtl433`.`locationTemperature` ;

CREATE TABLE IF NOT EXISTS `rtl433`.`locationTemperature` (
  `dateRecorded` DATETIME NOT NULL,
  `locationId` VARCHAR(25) NOT NULL,
  `temperatureFahrenheit` DECIMAL(5,2) NULL DEFAULT NULL,
  `humidity` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`dateRecorded`, `locationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rtl433`.`sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rtl433`.`sensor` ;

CREATE TABLE IF NOT EXISTS `rtl433`.`sensor` (
  `id` VARCHAR(25) NOT NULL,
  `description` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rtl433`.`sensorReading`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rtl433`.`sensorReading` ;

CREATE TABLE IF NOT EXISTS `rtl433`.`sensorReading` (
  `dateRecorded` DATETIME NOT NULL,
  `sensorId` VARCHAR(25) NOT NULL,
  `temperatureCelsius` DECIMAL(5,2) NULL DEFAULT NULL,
  `humidity` DECIMAL(5,2) NULL DEFAULT NULL,
  `batteryLow` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`dateRecorded`, `sensorId`),
  INDEX `sensorReading_sensor_idx` (`sensorId` ASC) VISIBLE,
  CONSTRAINT `sensorReading_sensor`
    FOREIGN KEY (`sensorId`)
    REFERENCES `rtl433`.`sensor` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `rtl433` ;

-- -----------------------------------------------------
-- procedure locationTemperatureInsert
-- -----------------------------------------------------

USE `rtl433`;
DROP procedure IF EXISTS `rtl433`.`locationTemperatureInsert`;

DELIMITER $$
USE `rtl433`$$
CREATE PROCEDURE `locationTemperatureInsert`(locationId VARCHAR(25), description VARCHAR(100),
											  dateRecorded DATETIME, temperature DECIMAL(5,2), humidity DECIMAL(5,2))
BEGIN
	DECLARE exit handler for sqlexception
    BEGIN
		ROLLBACK;
        SELECT 'An error has occurred, operation rollbacked and the stored procedure was terminated';
	END;

	START TRANSACTION;
	INSERT IGNORE INTO 
		location (id, description) 
	VALUES 
		(locationId, description);
    
    INSERT INTO 
		locationTemperature (dateRecorded, locationId, temperatureFahrenheit, humidity)
    VALUES
		(dateRecorded, locationId, temperature, humidity);

	COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sensorReadingInsert
-- -----------------------------------------------------

USE `rtl433`;
DROP procedure IF EXISTS `rtl433`.`sensorReadingInsert`;

DELIMITER $$
USE `rtl433`$$
CREATE PROCEDURE `sensorReadingInsert`(sensorId VARCHAR(25), dateRecorded DATETIME, batteryLow TINYINT(1),
                                        temperatureCelsius DECIMAL(5,2), humidity DECIMAL(5,2))
BEGIN

	DECLARE exit handler for sqlexception
    BEGIN
		ROLLBACK;
	END;

	START TRANSACTION;
	INSERT IGNORE INTO 
		sensor (id) 
	VALUES 
		(sensorId);
    
    INSERT INTO 
		sensorReading (dateRecorded, sensorId, temperatureCelsius, humidity, batteryLow)
    VALUES
		(dateRecorded, sensorId, temperatureCelsius, humidity, batteryLow);

	COMMIT;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
